+incdir+/home/openclaw/project/bus/AXI/rtl
/home/openclaw/project/bus/AXI/rtl/axi_addr_decoder.v
/home/openclaw/project/bus/AXI/rtl/axi_master.v
/home/openclaw/project/bus/AXI/rtl/axi_slave_sram.v
/home/openclaw/project/bus/AXI/rtl/axi_slave_dfi.v
/home/openclaw/project/bus/AXI/rtl/axi_crossbar_wr.v
/home/openclaw/project/bus/AXI/rtl/axi_crossbar_rd.v
/home/openclaw/project/bus/AXI/rtl/axi_interconnect.v
/home/openclaw/project/bus/AXI/rtl/axi_top.v
